name: cn_datetime_utils
description: A Flutter package add more power to default DateTime and Duration class.
version: 0.0.1
homepage: https://github.com/cn20082000/cn_datetime_utils
repository: https://github.com/cn20082000/cn_datetime_utils
issue_tracker: https://github.com/cn20082000/cn_datetime_utils/issues

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
